[package]
name = "crate-name-finder"
version = "0.1.0"
edition = "2021"
description = "Find unused crates.io crate names"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
climb = "2.0.5"
crates-index = "0.18.11"
rayon = "1.6.1"
